version: "3.7"

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: bank_details
    ports:
      - 5430:5432

  spring:
    image: alenjam/bankdetails:0.0.1-SNAPSHOT
    ports:
      - "8080:8080" 
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_details 
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin@123